export const GIRL_IDEAS: string[] = [
  'A café hopping day where you visit 2–3 aesthetic cafés, try desserts, and take photos.',
  'A shopping + thrift day in malls or vintage stores, followed by a casual meal.',
  'A spa or DIY spa day with facials, nails, hair masks, and chill music.',
  'A photoshoot outing in a garden, fort, or pretty street—dress up and click portraits.',
  'A workshop day like pottery, painting, candle-making, or perfume-making.',
  'A brunch + gossip session at a nice restaurant with relaxed vibes.',
  'A sunset beach or sea-face walk (like Marine Drive) with ice cream and chats.',

  'A library or bookstore date exploring books and having coffee together.',
  'A baking day at home where you try cakes, cookies, or brownies together.',
  'A creative DIY crafts day making scrapbooks, vision boards, or gifts.',
  'A museum or art gallery visit followed by café hopping.',
  'A karaoke night singing favorite songs and just having fun.',
  'A Pilates or yoga class followed by smoothie or healthy brunch.',

  'Café hopping in Bandra with aesthetic stops around Pali Hill and Chapel Road.',
  'Sunset photoshoot at Marine Drive with ethnic or western outfits.',
  'Shopping at Colaba Causeway followed by street food and Colaba cafés.',
  'Relaxed walk + ice cream date at Carter Road promenade.',
  'Art + café day around Kala Ghoda galleries and cute coffee spots.',
  'Shopping spree at Linking Road, Bandra with thrift + street fashion finds.',

  'Hot chocolate café date watching heavy rains from a window seat.',
  'Shopping + umbrella walk in Colaba Causeway during drizzle.',
  'Cozy indoor spa day with music and face masks during storms.',
  'Rainy photoshoot with aesthetic umbrellas and monsoon outfits.',

  'A simple café date in Bandra or Fort with light conversation.',
  'Ice cream + walk at Carter Road or Marine Drive.',
  'Bookstore browsing + coffee date for a calm vibe.',
  'Casual brunch at a nice but quiet restaurant.',

  'Planning aesthetic weekend getaways together.',
  'Trying new cafés and rating them like a ritual.',
  'Creating scrapbook or memory box of your time together.',
  'Learning a hobby together like dance or pottery.',

  "Picnic in the Park",
  "Dinner at a New Restaurant",
  "Cooking Class",
  "Outdoor Movie Night",
  "Sunset Viewing",
  "Vintage Shopping",
  "Art or Photography Walk",
  "Baking Challenge",
  "Bookstore Date",
  "DIY Spa Night",
  "Themed Dinner Night",
  "DIY Craft Night",
  "Book Club for Two",
  "Indoor Picnic",
  "Photo Shoot"
];

export const BOY_IDEAS: string[] = [
  'A sports day like cricket, football, badminton, or turf matches.',
  'An arcade + bowling night with friendly competition and food after.',
  'A tech or gadget exploration day, like gaming zones or electronics markets.',
  'A road trip or bike ride with no fixed plan, just exploring new places.',
  'A gym or fitness challenge day (workout + protein meal together).',
  'A street food tour across different areas trying spicy and local dishes.',
  'An adventure activity like go-karting, paintball, or trekking nearby hills.',

  'A gaming marathon day with consoles, PC games, and snacks.',
  'A movie marathon of a favorite franchise with popcorn and drinks.',
  'A fishing or outdoor chill day near a lake or quiet spot.',
  'A photography walk capturing street life, sunsets, and architecture.',
  'A car/bike detailing or modification day with friends.',
  'A music jam session or learning instruments together.',

  'Cricket match or turf game in local Mumbai grounds with friends.',
  'Evening at Worli Sea Face watching waves and skyline vibes.',
  'Street food crawl at Mohammad Ali Road or Girgaon Chowpatty.',
  'Gaming + arcade night in malls like Phoenix or R City.',
  'Bike ride through Bandra–Worli Sea Link and coastal roads.',
  'Fitness + gym session followed by protein shake at a café.',

  'Monsoon drive to Lonavala for foggy hills and chai stops.',
  'Maggi + chai at roadside stalls during heavy rain.',
  'Football or turf match in light rain for fun chaos.',
  'Long bike ride through wet coastal roads with rain gear.',

  'Coffee + dessert date at a calm café (no pressure vibe).',
  'Walk at Marine Drive or Worli Sea Face with snacks.',
  'Arcade + soft competition to break the ice.',
  'Simple street food + dessert hopping in a chill area.',

  'Gym or fitness goals together with shared progress tracking.',
  'Gaming nights or movie franchises as a ritual.',
  'Road trips planned together every few months.',
  'Trying new street food spots and ranking them.',

  "Food Truck Festival",
  "Movie Marathon",
  "Stargazing",
  "Arcade or Bowling",
  "Live Music or Theater",
  "Geocaching Adventure",
  "Scavenger Hunt",
  "Vintage Shopping",
  "Art or Photography Walk",
  "DIY Cocktail Making",
  "Game Night",
  "Home Movie Theater",
  "Cook-Off Challenge",
  "Karaoke Night"
];

export const COUPLE_IDEAS: string[] = [
  'A sunset date + long walk (beach, fort, or skyline point).',
  'A movie + dinner combo date—the classic but always works.',
  'A stay-at-home cozy night with cooking together, movies, and games.',
  'A surprise date challenge where each person plans half the day.',
  'A mini road trip to a nearby hill station, café, or beach town.',
  'A bucket-list day—doing 3–4 small things like food, arcade, shopping, dessert.',
  'A memory-making date: polaroid photos, handwritten notes, and a time capsule box.',

  'A stargazing night with blankets, snacks, and quiet music.',
  'A theme date (dress in a color/theme and plan the day around it).',
  'A cooking battle where you both make dishes and judge each other.',
  'A game night with board games, cards, or video games.',
  'A ferry ride or boat experience with scenic views and photos.',
  'A sunrise date with early morning walk and breakfast together.',

  'Sunset at Marine Drive followed by chai and long talks.',
  'Romantic walk at Bandstand Bandra near the fort and sea.',
  'Gateway of India visit with ferry ride to Elephanta Caves.',
  'Beach date at Juhu Beach with bhel, ice cream, and sunset.',
  'Cute café date hopping in Bandra or Fort area.',
  'Evening drive through Worli Sea Face during high tide.',

  'Watching rains together at Marine Drive with snacks and chai.',
  'Lonavala or nearby hill station day trip during peak monsoon.',
  'Cozy indoor movie + cooking night while it rains outside.',
  'Street food + umbrella walk in Fort or Bandra lanes.',

  'Coffee date + long walk to keep it simple and real.',
  'Ice cream + seaside walk (Marine Drive or Bandra).',
  'Casual lunch + small walk in a mall or promenade.',
  'Street food + exploring nearby lanes together.',

  'Monthly “date bucket list” where you try new experiences together.',
  'Cooking challenges and trying different cuisines at home.',
  'Weekend mini trips around Mumbai (Lonavala, Alibaug, Igatpuri).',
  'Creating shared playlists, photos, and yearly memory albums.',

  "Picnic in the Park",
  "Dinner at a New Restaurant",
  "Cooking Class",
  "Movie Marathon",
  "Outdoor Movie Night",
  "Stargazing",
  "Arcade or Bowling",
  "Live Music or Theater",
  "Sunset Viewing",
  "Potluck Dinner Party",
  "Scavenger Hunt",
  "Baking Challenge",
  "Bookstore Date",
  "DIY Cocktail Making",
  "DIY Spa Night",
  "Themed Dinner Night",
  "Home Movie Theater",
  "Cook-Off Challenge",
  "Indoor Picnic",
  "Karaoke Night",
  "Photo Shoot"
];
